#!/bin/zsh

alias ls='ls --color=auto'
#alias ll='ls -lsah --color=auto'
alias ll='exa -la --git --group --group-directories-first'
alias l='exa -l --git --group --group-directories-first'
alias bc='bc -q'

alias config="git --git-dir=$HOME/repos/public/corium/.git --work-tree=$HOME/repos/public/corium/"
alias config-ls="config ls-tree master -rt | cut -c 54- | sed 's/^\.//;s/[a-zA-Z]*\//| /g'"

alias sc='systemctl'
alias scu='systemctl --user'

alias bt='bluetoothctl'

# Git
alias glog='git log --graph'

# CD aliases

alias cr='cd ~/repos'
crl() {cd ~/repos/local/$( ls -1 ~/repos/local | fzf )}
crg() {cd ~/repos/github/$( ls -1 ~/repos/github | fzf )}
crs() {cd ~/repos/star/$( ls -1 ~/repos/star | fzf )}
cri() {cd ~/repos/inhouse/$( ls -1 ~/repos/inhouse | fzf )}
crt() {cd ~/repos/practicas/$( ls -1 ~/repos/practicas | fzf )}
crp() {cd ~/repos/public/$( ls -1 ~/repos/public | fzf )}

alias cds='cd ~/.sources'
alias cdb='cd ~/.local/bin'
alias cdc='cd ~/.config'

alias cdd='cd ~/dox/downloads'

alias cb='cd $OLDPWD'

#==============================================================================
#==========                   Conditional aliases                    ==========
alias_if_installed() { which $1 > /dev/null && alias $2 || { [ "$3" != "" ] && alias $3 || alias $(echo $2 | cut -d'=' -f 1)="echo '[alias_if_installed] ERROR: [$1] is not installed.'" };}
#======================================----------------------------------------

# Terminal Ease aliases
alias_if_installed nvim v='nvim -i ~/.cache/vim/info' v='vim'
alias_if_installed ranger r='ranger'
alias_if_installed zathura z='zathura'
alias_if_installed highlight ccat='highlight --out-format=ansi'
alias_if_installed matlab matlab='matlab & disown; sleep 10 && exit'

alias_if_installed i3lock i3lock='i3lock -c 06060a'
alias_if_installed i3lock-fancy i3lock='i3lock-fancy -p'

alias_if_installed axel wget='axel -a -n 16'

#==============================================================================
#==========                   Function Aliases                       ==========

se() { TMP=$( du -a ~/.local/bin/scripts/ | cut -f2 | sort | fzf --prompt="EDIT » " ) ; [[ $? -eq 0 ]] && $EDITOR $TMP ;}

ns() { SCRIPT="$1" ; [[ $SCRIPT == "" ]] || { [[ -f ~/.local/bin/scripts/$SCRIPT ]] || { echo "#!/bin/bash" > ~/.local/bin/scripts/$SCRIPT && chmod +x ~/.local/bin/scripts/$SCRIPT && v ~/.local/bin/scripts/$SCRIPT } } ;}

pac() { TMP=$( pacman -Ss | awk 'NR%2{printf "%s¬",$0;next;}1' | sed 's/   //' | column -s'¬' -t -E1 | fzf ) ; [[ $? -eq 0 ]] && TMP=$( echo $TMP | cut -d ' ' -f1 | cut -d '/' -f2 ) && pacman -Si $TMP && sudo pacman -S $TMP ;}

ya() { TMP=$( paru -Sl aur | cut -c 5- | sed 's/ unknown-version//;s/ \[Ins/¬[Ins/' | column -s'¬' -t | fzf ) ; [[ $? -eq 0 ]] && TMP=$( echo $TMP | cut -d ' ' -f1 | cut -d '/' -f2 ) && paru -Si $TMP && read && paru -S $TMP ;}

checkpass() { curl -s https://api.pwnedpasswords.com/range/$( echo -n $1 | sha1sum | tr '[a-z]' '[A-Z]' | cut -c -5 ) | grep $( echo -n $1 | sha1sum | tr '[a-z]' '[A-Z]' | cut -c 6- ) ;}

