#!/bin/sh

export XDG_CONFIG_HOME="$HOME/.config"

export PATH=$PATH:$HOME/.local/bin
export PATH=$PATH:$HOME/.local/bin/scripts

export EDITOR=/bin/nvim

export _JAVA_AWT_WM_NONREPARENTING=1 # 'tis for IntelliJ to actually function

export BC_ENV_ARGS=$HOME/.config/bc/bc.env	# Sets env vars for bc calculator

# fzf default settings
export FZF_DEFAULT_OPTS="--layout=reverse --height 50% --no-bold --color='bg+:#ec9a0a,fg+:#060604,gutter:0,hl+:1,prompt:#fcae1e'"

# home directories and caches and stuff to keep home tidy
export GNUPGHOME="~/.config/gnupg"
export WWW_HOME="~/.config/w3m"
export __GL_SHADER_DISK_CACHE_PATH="~/.cache/nv"
export VIMINIT=":set runtimepath^=$HOME/.config/vim|:source $HOME/.config/vim/vimrc"

export HISTFILE="$HOME/.cache/shell_hist"

export ZSH_CUSTOM="$HOME/.config/zsh/.oh-my-zsh"
export ZSH_COMPDUMP="$HOME/.cache/zcompdump"

export NPM_CONFIG_USERCONFIG="$HOME/.config/npm/npmrc"

export PLATFORMIO_CORE_DIR="$HOME/.local/share/platformio"
